codecov:
  branch: dev
coverage:
  range: 50...90
  status:
    project:
      default:
        enabled: yes
        target: 50%
    patch:
      default:
        enabled: yes
        target: 50%
ignore:
  - /example/cmd/excited
  - /example/gen/go/uber/foo/v1
  - /example/gen/go/uber/bar/v1
  - /internal/cmd/testdata/grpc/gen/grpcpb
  - /internal/reflect/gen/uber/proto/reflect/v1
