project_name: prototool

builds:
- main: ./cmd/prototool
  id: "prototool"
  binary: prototool
  goos:
    - linux
    - darwin
    - windows
  goarch: [amd64]

archives:
  - files:
      - ./assets/dist/*

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

dockers:
  - id: "prototool"
    dockerfile: Dockerfile
    image_templates:
    - "gcr.io/hnlq715/prototool:latest"