steps:
  - name: ':docker: :package:'
    plugins:
      - docker-compose#v3.0.2:
          build: buildkite
          image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - name: ':make:'
    command: make all codecov
    plugins:
      - docker-compose#v3.0.2:
          run: buildkite
    agents:
      queue: workers
